### ISSUE TITLE
AutoFormat doesn't work with Play version 2.3.10

### ISSUE THREAD

**Issue by d3lavar** [Sciss/play-json-sealed#5]
I'm using scala version 2.11.8 and AutoFormat macro throws an exception during compile
```
/test/SimpleTest.scala:18: exception during macro expansion: 
[error] java.lang.NoSuchMethodError: play.api.libs.json.JsMacroImpl$.formatImpl(Lscala/reflect/macros/whitebox/Context;Lscala/reflect/api/TypeTags$WeakTypeTag;)Lscala/reflect/api/Exprs$Expr;
[error]         at de.sciss.play.json.AutoFormat$.applyImpl(AutoFormat.scala:52)
[error]     implicit val fooWrites = AutoFormat[Foo]
```

It happens coz there is an old method **readsImpl** in Play 2.3.10 instead of **formatImpl** in newer Play versions.

**Comment by Sciss** [comment]
Cannot reproduce. The library is built exactly against Play 2.3.10 under Scala 2.11.x; `JsMacroImpl` has all of `readsImpl`, `writesImpl`, `formatImpl`. Your error indicates that you are mixing with an incompatible version of Play.

**Comment by d3lavar** [comment]
You are right, I'm using play 2.5.12. But what is the problem to compile macro against Play 2.5.x?

**Comment by Sciss** [comment]
The problem is that Lightbend has a non-policy of taking care of legacy systems. Scala 2.11.x given Java 6 compatibility promise, which Lightbend products such as Play and Akka simply break because they don't care if you are not a paying customer. 2.3.10 is the last Play version to support Java 6. If you need Java 8 support, pressure them to realise a stable Play version for Scala 2.12. Of course you can create your own artifact with Scala 2.11 and Play 2.5.x; they should be source compatible.
